config/routes.rb
Rails.application.routes.draw do
  

  get 'friends/index'

  get 'friends/destory'

  resources :friend_requests
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :images do
  end
  resources :freeusers, only: [:show, :destroy, :index, :edit] do
    collection do
      post :search, to: 'freeusers#search'
    end
  end

  resources :albums
  devise_for :users, :controllers => { :registrations => 'registrations'}
  
  get '/show_image/:id', :controller => 'albums', :action => 'show_image'

  post 'search_images', to: "images#search"
  post 'search_images_album', to: "albums#search"
  post 'search_freeusers', to: "freeusers#search"
  
  match "/404" => "errors#error404", via: [ :get, :post, :patch, :delete ]
  root 'welcome#index'

  get 'angular_test', to: "angular_test#index"

end

app/models/freeuser.rb
# class Freeuser < ActiveRecord::Base
# 	# has_secure_password
# 	# has_many :images
# 	# has_many :users
# 	# before_save { self.email = email.downcase }
# 	# VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
# 	# validates :name, presence: true, length: { minimum: 3, maximum: 100 }
# 	# validates :email, presence: true, length: { maximum: 105 }, uniqueness: { case_sensitive: false }, format: { with: VALID_EMAIL_REGEX }


#   def self.search(email)
#     names_array = name.split(' ')
#     if names_array.size == 1
#       where('email LIKE ?', "%#{names_array[0]}%", "%#{names_array[0]}%").order(:email)
#     else
#       where('email LIKE ? or email LIKE ?', 
#     "%#{names_array[0]}%", "%#{names_array[1]}%", "%#{names_array[0]}%", "%#{names_array[1]}%").order(:email)
#     end 
#   end

# end

app/controllers/freeusers_controller.rb
class FreeusersController < ApplicationController
	# skip_before_action :authenticate_user!
	before_action :require_admin, except: [:search]
	before_action :set_user, only: [:edit, :update, :show, :destroy, :admin_change, :require_super_user]
	before_action :require_super_user, only: [:edit, :destroy]
	before_action :set_super_user, only: [:edit, :destroy, :index, :search]

	
	

	def index
		# @freeusers = User.all
		@freeusers = User.paginate(page: params[:page], per_page: 20).order(email: :asc)
	end

  def show
  	@images = Image.all.order(updated_at: :desc)
  end

  def edit
  	if current_user.admin && current_user == User.find_by(email: 'sammydallal@gmail.com')
    	admin = @user
    	admin.toggle!(:admin) unless current_user == @user
    	flash[:success] = "#{@user.full_name}'s admin status has been changed" unless current_user == @user
    	redirect_to freeusers_path
    else
    	flash[:danger] = "#{current_user.full_name} doesn't have the ability to change admin status"
    	redirect_to :back
    end
    # admin = @user
    # admin.toggle!(:admin) unless current_user == @user
    # redirect_to :back
  end

	def destroy
		if !@user.admin?
	  	@user.destroy unless current_user == @user
	  	flash[:danger] = "User and all images and albums have been deleted"
	  	redirect_to images_path
	  else
	  	flash[:danger] = "You can not delete an Admin account"
	  	redirect_to :back
	  end
  end 

  # def searchuser
  #   @users = User.search(params[:search_param])
  #   # puts @images
  #   if @users
  #     # @users = current_user.except_current_user(@users)
  #     render partial: "lookup"
  #   else
  #     render status: :not_found, nothing: true
  #   end
  #   respond_to do |format|
  #   	format.js
  #   end
  # end
  def search
  	@users = User.search_by_name(params[:search_name]).paginate(:page => params[:page])
  end
	# def login
	# 	user = User.find_by(email:params[:session][:email].downcase)
	# 		if user && user.authenticate(params[:session][:password])
	# 			session[:user_id] = freeuser.id
	# 			@current_user = Freeuser.find(session[:user_id])
	# 			flash[:success] = "You are logged in"
	# 			redirect_to images_path(user)
	# 		else
	# 		flash.now[:danger] = "Invalid email or password"
	# 		render :new	
	# 	end
	# end	
	
	private

	def set_user
		@user = User.find(params[:id])
	end

	def require_super_user
		unless current_user == User.find_by(email: 'sammydallal@gmail.com') || current_user == @user
	  		flash[:info] = "You must be the appilcation owner to perform that action"
	  		redirect_to freeusers_path
      	end
  	end

  	def set_super_user
  		@super_user = User.find_by(email: 'sammydallal@gmail.com')
  	end
end

app/views/freeusers/_lookup.html.erb
<%- model_class = User -%>
<% if current_user.admin? %>
<div id="user-lookup">
  	
	
  	<table class="search-results-table col-md-12 table table-striped">
    <thead>
      <tr> 
        <th><%= model_class.human_attribute_name(:full_name) %></th>
        <th><%= model_class.human_attribute_name(:email) %></th>
        <th><%= model_class.human_attribute_name(:admin) %></th>
        <th><%= model_class.human_attribute_name(:updated_at) %></th>
        <th><%=t '.actions', :default => t("helpers.actions") %></th>  
      </tr>
    </thead>
    <tbody>

  		<tbody>          
  			<% @freeusers.each do |user| %>  
  			<tr>
            <td><%= user.full_name %></td>
  				  <td><strong><%= link_to user.email, freeuser_path(user) %></strong></td>
            <td style="color: darkred;"><%= user.admin %></td>
			      <td><%= time_ago_in_words (user.updated_at) %> ago</td>
            <% if current_user == @super_user || current_user == user %>
             <td>
              <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                          freeuser_path(user),
                          :method => :delete,
                          :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                          :class => 'btn btn-xs btn-danger' %>
              <% if current_user == @super_user %>
                <%=link_to 'change admin', edit_freeuser_path(user), :class => 'btn btn-xs btn-primary' %>
              <% end %>            
            </td>
            <% else %>
                  <td>Account Locked <br><p style="color: darkred;"><%= user.email %></p> </td>
            <% end %>            
      		</tr>	 	
    		<% end %>          
        <% end %>          
    	</tbody>
	</table> 
  <% else %>	
  	  		
     <div id="user-lookup-errors"></div>
    </div>


</div> 
 
<div class="flickr_pagination">
    <div class="page_info">
     
    </div>
    <%= will_paginate  %>
  </div>

  
 

app/views/freeusers/index.html.erb
<%= render :partial => 'lookup' %>

app/views/freeusers/new.html.erb
<div class="row">
  <div class="col-xs-12">
    <%= form_for(@user, :html => {class: "form-horizontal", role: "form"}) do |f| %>
      <div class="form-group">
        <div class="control-label col-sm-2">  
          <%= f.label :email %>
        </div>
        <div class="col-sm-8">  
          <%= f.email_field :email, rows: 10, class: "form-control", placeholder: "Enter Email" %>
        </div>  
      </div>
      <div class="form-group">  
        <div class="control-label col-sm-2">  
          <%= f.label :password %>
        </div>
        <div class="col-sm-8">
          <%= f.password_field :password, class: "form-control", placeholder: "Password" %>
        </div>
      </div>  
      <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
          <%= f.submit class: 'btn btn-danger btn active'%>
        </div>
      </div>    
      
    <% end %>
    <div class="col-xs-4 col-xs-offset-4">
      <%= link_to "Cancel request and return to home page", root_path %>
    </div>  
  </div>
</div> 

app/views/freeusers/search.html.erb
<%- model_class = User -%>


  <%= will_paginate @users, renderer: BootstrapPagination::Rails %>
</div>

<table class="search-results-table col-md-12 table table-striped">
	<thead>
    <tr> 
      <th>Full Name</th>
      <th>Email</th>
      <% if current_user.admin? %>
      	<th>Admin</th>
      <% end %>
      <th>Updated At</th>
      <th>Actions</th>  
    </tr>
  </thead>

	<tbody>          
			<% if @users.size < 1 %>
				<h3 align="center"> No users found </h3> 
			<% else %>
			<% @users.each do |user| %> 
			<tr>
		      <td><%= user.full_name %></td>
		      <% if current_user == @super_user %>
				  	<td><strong><%= link_to user.email, freeuser_path(user) %></strong></td>
				  	<td><%= user.admin %></td>
				  <% else %>
				  	<td>Must be friends to see email address</td>	
				  <% end %>
		      <td><%= time_ago_in_words (user.updated_at) %> ago</td>
		       <td>
		       	<% if current_user == @super_user%> 
		          <%=link_to 'Add Friend', friend_requests_path(friend_id: user.id), method: :post, :class => 'btn btn-xs btn-primary' %> 
		          	<%= link_to 'Admin?', edit_freeuser_path(user), :class => 'btn btn-xs btn-danger'%>  
		          <% else %>
		          	<%= link_to 'Add Friend', '#', method: :post, :class => 'btn btn-xs btn-primary'%>
		          <% end %>      
		      </td>            
				</tr>
				<% end %>	 	
			<% end %>          

	</tbody>
</table>

app/views/freeusers/show.html.erb
<%- model_class = Image -%>
<h3 align="center"> <%= "User: " + @user.full_name %></h3>


<% if !@user.admin? || current_user == User.find(1) %>
	<div class="col-xl-5 col-xs-offset-9" style="margin-top: -50px; padding-bottom: 10px;">
		<%= link_to "Delete User", freeuser_path(@user), method: :delete, data: { confirm: "Are you sure you want to delete #{@user.email}?" }, class: "btn btn-lg btn-danger" %>
	</div>
<% end %>

<div id="image-lookup">
	<h3>Search for images</h3>
	  <%= form_tag search_images_path, remote: true, method: :post, id: 'image-lookup-form' do %>
	  <div class="form-group row no-padding text-center col-md-8">
		    <div class="col-md-8">
		      <%= text_field_tag :search_param, params[:search_param], autofocus: true,
		                                                          class: 'form-control search-box input-sm' %>
		    </div>
		    <div class="col-md-2">
		      <%= button_tag(type: :submit, class: "btn btn-sm btn-success") do %>
		        <i class="fa fa-search"></i> Search Images

		      <% end %>          
		      <% end %>

		   	</div>  
	   </div> 
	   <div class="col-md-">
	      <%= link_to t('.back', :default => t("helpers.links.back")),
                    freeusers_path, :class => 'btn-sm btn-info btn active'  %> 
        </div>
	

		<table class="search-results-table col-md-12 table table">
        <thead>
          <tr>  
            <th><%= model_class.human_attribute_name(:title) %></th>
            <th><%= model_class.human_attribute_name(:picture) %></th>
            <th><%= model_class.human_attribute_name(:updated_at) %></th>
            <th><%= model_class.human_attribute_name(:Photo_by) %></th>
            <th>Action</th>
          </tr>
        </thead>
        <div align="center" style="font-size: 16px;">
      </div>  
	    		<tbody>
	    			<% @images.each do |image| %>
              		<% if @user == image.user %>
	    			<tr>
	    				  <td><strong><%= link_to image.name, image_path(image) %></strong></td>
	            		  <td><a href="/images/<%= image.id %>"><%= image_tag image.picture.url, width: "150" %></a></td>
					      <td><%= time_ago_in_words (image.updated_at) %> ago</td>
					      <td><strong><%= image.credit %></strong></td>
					      <% if !@user.admin? || current_user == @user || current_user == User.find_by(email: 'sammydallal@gmail.com') %>
					      <td> 
			                  <%= link_to t('.edit', :default => t("helpers.links.edit")),
			                              edit_image_path(image), :class => 'btn-xs btn-info btn' %>
			                  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
			                              image_path(image),
			                              :method => :delete,
			                              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
			                              :class => 'btn btn-xs btn-danger' %>
                		  </td>
                		  <% else %>
                		  	<td><p style="color: darkred;">Admin Account Locked</p><td>
                		  <% end %>
			              
	        		</tr>	 	
	      		<% end %>
            
            <% end %>
	      	</tbody>
    	</table> 

 
    
	     		