config/routes.rb
Rails.application.routes.draw do
  

  get 'friends/index'

  get 'friends/destory'

  resources :friend_requests
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :images do
  end
  resources :freeusers, only: [:show, :destroy, :index, :edit] do
    collection do
      post :search, to: 'freeusers#search'
    end
  end

  resources :albums
  devise_for :users, :controllers => { :registrations => 'registrations'}
  
  get '/show_image/:id', :controller => 'albums', :action => 'show_image'

  post 'search_images', to: "images#search"
  post 'search_images_album', to: "albums#search"
  post 'search_freeusers', to: "freeusers#search"
  
  match "/404" => "errors#error404", via: [ :get, :post, :patch, :delete ]
  root 'welcome#index'

  get 'angular_test', to: "angular_test#index"

end

app/models/album.rb
class Album < ActiveRecord::Base
  has_many :image_albums
  has_many :images, through: :image_albums
  # has_many :images
  validates :name, presence: true, length: { minimum: 3, maximum: 25 }
  belongs_to :user
  # acts_as_taggable
  # acts_as_taggable_on :skills


end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  devise :timeoutable, :timeout_in => 180.minutes       
  has_one :payment
  accepts_nested_attributes_for :payment
  has_many :images, dependent: :destroy
  has_many :albums, dependent: :destroy
  has_many :friend_requests, dependent: :destroy
  has_many :pending_friends, through: :friend_requests, source: :friend
  has_many :friendships, dependent: :destroy
  has_many :friends, through: :friendships

  validates :first_name, presence: true
  validates :last_name, presence: true
  # rails_admin do 
  #   object_label_method :email 
  # end 
  # acts_as_taggable

  def full_name
    "#{first_name} #{last_name}"
  end


  def self.search_by_name(name) 
    return User.none if name.blank?
    names_array = name.split(' ')
    if names_array.size == 1
      where('first_name LIKE ? or last_name LIKE ?', "%#{names_array[0]}%", "%#{names_array[0]}%").order(:first_name)
    else
      where('first_name LIKE ? or first_name LIKE ? or last_name LIKE ? or last_name LIKE ?', 
    "%#{names_array[0]}%", "%#{names_array[1]}%", "%#{names_array[0]}%", "%#{names_array[1]}%").order(:first_name)
    end 
  end

  def remove_friend(friend)
    current_user.friends.destroy(friend)
  end
	
end	

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
 	before_action :set_album, only: [:edit, :update, :destroy, :show, :require_super_user]
 	before_action :require_same_user, only: [:edit, :update, :destroy, :show]
 	before_action :require_super_user, only: [:edit, :destroy, :update]
 	before_action :set_super_user, only: [:index, :show]
 	before_action :demo_account, only: [:destroy, :update, :create]
	
	def index
		if current_user.admin?
			@albums = Album.all.order(user_id: :asc)
		else
			@albums = Album.where(user_id: current_user.id)
		end	
		# @albums = Album.paginate(page: params[:page], per_page: 5).order(name: :asc)
		@images = Image.where(user_id: current_user)
	end

	def new
	  @album = Album.new
  	end


	def show
		# @image_albums = @album.images.paginate(page: params[:page], per_page: 5).order(updated_at: :desc)
    	@image_albums = @album.images.all.order(updated_at: :desc)
    	@id = User.find(@album.user_id) # in view page you can use User.find(@album.user_id).email 
	end

	def show_image
		# @album = Album.where(user_id: current_user)
		@image = Image.find(params[:id])
		# @album = @image.album(image_id: @image.id) 
		@album = Album.find_by(user_id: current_user) 
		@image_albums = @album.images.all.order(updated_at: :desc)
		@id = User.find(current_user)
		#need to make an albumimage controller to display single images with thumbnails from just the album
	end

	def create
		@album = Album.new(album_params)
		# @album.user_id = current_user.id 
		if @album.save
			flash[:success] = "You have created a new Album"
			redirect_to albums_path(current_user)
		else
			flash[:danger] = "Album was not created please try again"
			redirect_to :back
		end
	end

	def destroy
		@album.destroy
		flash[:danger] = "Album was destroyed"
		redirect_to albums_path
	end

	def update
		if @album.update(album_params)
			flash[:success] = "Album was successfully updated"
			redirect_to album_path(@album)
		else
      		flash[:danger] = "Album name must be at least 3 characters long or a maximum of 25 characters long"
			redirect_to :back
		end
	end

	def search
    @images = Image.search(params[:search_param])
    # puts @images
    if @images
      # @users = current_user.except_current_user(@users)
      render :show
      # render partial: "lookup"
    else
      render status: :not_found, nothing: true
    end
  end


  private

		def album_params
	  	params.require(:album).permit(:name).merge(user: current_user)
		end

  	def set_album
  		 @album = Album.find(params[:id])
    end

		def require_super_user
			unless current_user == User.find_by(email: 'sammydallal@gmail.com') || current_user.id == @album.user_id
			  flash[:info] = "You can only edit or delete your own Albums"
			  redirect_to albums_path
			end
		end

		def require_same_user
	    if current_user.id != @album.user_id and !current_user.admin?
	      flash[:danger] = "You can only view, edit or delete your own albums"
	      redirect_to albums_path
	    end
	  end

	  def set_super_user
	    @super_user = User.find_by(email: 'sammydallal@gmail.com')
	  end

end

app/views/albums/_form.html.erb
_form.html.erb

app/views/albums/edit.html.erb
<h1 align="center"> <%= "Update Album: " + @album.name %></h1>


<%= form_for(@album, :html => {class: "form-horizontal", role: "form"}) do |f| %>
	<div class="form-group">
		<div class="control-label col-sm-2">	
			<%= f.label :name %>
		</div>
		<div class="col-sm-8">
			<%= f.text_field :name, class: "form-control", placeholder: "Category name", autofocus: true %>
		</div>
	</div>
	
	<div class="form-group">
		<div class="col-sm-offset-2 col-sm-10">
			<%= f.submit class: 'btn btn-danger btn active'%>
		</div>
	</div>		
	
<% end %>
<div class="col-xs-4 col-xs-offset-4">
	<%= link_to "Cancel request and return to albums", albums_path %>
</div>	

app/views/albums/index.html.erb
<h1 align="center">Listing all Albums</h1>
<div id="welcome_background">
	<div align="center" style="width: 1150px; height: 800px; overflow: scroll">		
		<% @albums.each do |album| %>	
			<ul class="listing">
				<div class="row">
					<div class="well col-md-4 col-md-offset-4" style="opacity: 0.6; margin-top: 15px; border: 1px solid grey;">
						<li class="article-title">
							<h3 style="margin-top: -5px;"><%= link_to "#{album.name}", album_path(album) %></h3>
						</li>
						<li><strong><%= pluralize(album.images.count, "images") %></strong></li>
						<% if current_user.admin %>
							<li><strong style="font-weight: bold; color: darkred;">Album Owner: <%= User.find(album.user_id).full_name %></strong></li>
						<% end %>
					</div>		
				</div>
			</ul>		
		<% end %>	
	 </div>	
</div> 

app/views/albums/new.html.erb
<h1 align="center">Create New Album</h1>



<%= form_for(@album, :html => {class: "form-horizontal", role: "form"}) do |f| %>
	<div class="form-group">
		<div class="control-label col-sm-2">	
			<%= f.label :name %>
		</div>
		<div class="col-sm-8">
			<%= f.text_field :name, class: "form-control", placeholder: "Album name", autofocus: true %>
		</div>
	</div>
	
	<div class="form-group">
		<div class="col-sm-offset-2 col-sm-10">
			<%= f.submit class: 'btn btn-danger btn active'%>
		</div>
	</div>		
	
<% end %>
<div class="col-xs-4 col-xs-offset-4">
	<%= link_to "Cancel request and return to your images", images_path %>
</div>	

app/views/albums/show.html.erb
<%- model_class = Image -%>

<h1 align="left"> <%= "Album: " + @album.name %></h1>
<% if current_user.admin? %> 
  <p style="font-weight: bold; color: darkred;">This Album Belongs to: <%= @id.full_name %> </p>
<% end %>  

<div align="right" style="margin-top: -30px;"> 
	<% if current_user == @super_user || current_user == @id %> 
		<div class="row">
			<%= link_to "Edit Album Name", edit_album_path(@album), class: "btn btn-xs btn-primary"%>
			<%= link_to "Delete Album", album_path(@album), method: :delete, data: { confirm: "Are you sure you want to delete this Album?" }, class: "btn btn-xs btn-danger" %>
    </div>
	<% end %>
</div>

	<br>
  <hr>
  <br>

<div id="image-lookup">
  <%= form_tag search_images_path, remote: true, method: :post, id: 'image-lookup-form' do %>
  <div class="form-group row no-padding text-center col-md-8">
    <div class="col-md-8">
      <%= text_field_tag :search_param, params[:search_param], autofocus: true,
                                                          class: 'form-control search-box input-sm' %>
    </div>
    <div class="col-md-2">
      <%= button_tag(type: :submit, class: "btn  btn-sm btn-success") do %>
        <i class="fa fa-search"></i> Look up a Images
 <% end %>
    </div>
  </div>
  <% end %>
  <div align="center">
  	<div id="image-lookup-results">
  	    	<table class="search-results-table col-md-12 table table-striped">
            <thead>
              <tr>  
                <th><%= model_class.human_attribute_name(:name) %></th>
                <th><%= model_class.human_attribute_name(:picture) %></th>
                <th><%= model_class.human_attribute_name(:Photo_by) %></th>
                <th><%=t '.actions', :default => t("helpers.actions") %></th>
              </tr>
            </thead>
            <tbody>
            	<% @image_albums.each do |photo| %>
            	<tr>
            		<td><%= photo.name %></td>
            		<td><strong><a href="/images/<%= photo.id %>"><%= image_tag photo.picture.url, width: "175" %></a></strong></td>
            		<td><%= photo.credit %></td>
            		<% if current_user.id == photo.user_id || current_user == @super_user %>
        				  <td><%= link_to "edit this photo", edit_image_path(photo), class: "btn btn-xs btn-primary" %>
        				      <%= link_to 'Delete', image_path(photo), class: 'btn btn-xs btn-danger', method: :delete, data: {confirm: 'Are you sure?'} %></td>
                <% else %>
                  <td>Account Locked: <br><p style="color: darkred;"><%= User.find(photo.user_id).email %></p> </td>
    				    <% end %> 
            	</tr>
              <% end %> 	
            </tbody>
          </table>
    </div>      	
  </div>
</div>

app/views/albums/show_image.html.erb
<%- model_class = Image -%> 
 
<div class="page-header" style="margin-top: -25px; padding-top: 5px;">
  <h1><%= @image.name %></h1>
  <% if current_user.admin? %>  
    <p style="font-weight: bold; color: darkred;">This Photo Belongs to: <%= @id.email %> </p>
  <% end %>

</div>       
    <div class="col-md-12">
      <div style="margin-top: -55px;" align="right">
      <%= link_to t('.back', :default => t("helpers.links.back")),
                    images_path, :class => 'btn-sm btn-info btn active'  %>
      <% if current_user == @super_user || current_user == @id %>              
      <%= link_to t('.edit', :default => t("helpers.links.edit")),
                    edit_image_path(@image), :class => 'btn-sm btn-success btn active' %>
                  
      <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                    image_path(@image),
                    :method => 'delete',
                    :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                    :class => 'btn-sm btn-danger btn active' %>
                  
      <% end %>              
      </div>
    </div>
<!-- <div class="col-lg-12">  -->   
  <dl style="margin-left: -60px;" class="dl-horizontal">
      <dt></dt>   
        <dd><%= image_tag(@image.picture.url, width: "1000") if @image.picture? %></dd>
        <div style="margin-top: 5px;">
          <dd><p class="pull-right" style="font-weight: italic; margin-right: 20px;"> Photo by: <%= @image.credit %></p></dd>
        </div> 
          <dd style="margin-top: -27px;">
              <% if @images.next(@image) %>
                <%= link_to 'Previous', @images.next(@image), :class => 'btn btn-xs btn-primary' %>
              <% else %>
                <% if @images.size >= 2 %>
                  <button class="btn btn-xs btn-danger btn active">First Image</button>
                <% end %>
              <% end %>
              <% if @images.previous(@image) %>
                <%= link_to 'Next', @images.previous(@image), :class => 'btn btn-xs btn-primary' %>
              <% else %>
                <% if @images.size >= 2 %>
                 <button class="btn btn-xs btn-danger btn active" style="margin-right: 10px;">Last Image</button>
                <% end %> 
              <% end %>
          </dd>
          <div class="imagebar" style="margin-top: 1px;">
          <% if @image_albums.size > 1 %>
            <% @image_albums.each do |image| %>
            <div style="display: inline-block;">
              <div class="thumbnail" style="width: 145px;">
                <a href="/show_image/<%= image.id %>"><%= image_tag image.picture.url %></a>
              </div> 
            </div>       
            <% end %> 
          <% end %>
          </div> 
          <%= form_for @image, :html => { multipart: true, :class => "form-horizontal image" } do |f| %>
            <div class="input-group" style="margin-top: -5px;">
              <div class="form-group">
                <div class="">
                  <div class=""> 
                  <% if !@id.admin? || current_user == @id || current_user == User.find_by(email: 'sammydallal@gmail.com') %> 
                  <%= f.label :albums, :class => 'control-label col-lg-3' %>
                    <%= f.collection_check_boxes :album_ids, Album.where(user_id: @id), :id, :name do |cb| %>
                      <% cb.label(class: "checkbox-inline input_checkbox") {cb.check_box(class: "checkbox") + cb.text }%>
                  <% end %> 
                  </div>  
                </div>
              </div>
              <span class="input-group-btn">
                <div class="">
                  <div class="col-lg-offset-0 col-lg-10">
                    <%= f.submit nil, :class => 'btn btn-sm btn-success' %>
                  </div>
                  <% end %>
                </div>
              </span>
            </div>  
        <% end %>  
        <div class="wrap">
            <dd><p><%= @image.caption %></p> </dd> 
        </div>   
  </dl>