config/routes.rb
Rails.application.routes.draw do
  

  get 'friends/index'

  get 'friends/destory'

  resources :friend_requests
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :images do
  end
  resources :freeusers, only: [:show, :destroy, :index, :edit] do
    collection do
      post :search, to: 'freeusers#search'
    end
  end

  resources :albums
  devise_for :users, :controllers => { :registrations => 'registrations'}
  
  get '/show_image/:id', :controller => 'albums', :action => 'show_image'

  post 'search_images', to: "images#search"
  post 'search_images_album', to: "albums#search"
  post 'search_freeusers', to: "freeusers#search"
  
  match "/404" => "errors#error404", via: [ :get, :post, :patch, :delete ]
  root 'welcome#index'

  get 'angular_test', to: "angular_test#index"

end

app/views/layouts/_header.html.erb
    <div class="navbar navbar-default navbar-fixed-top">
      <div class="fluid-container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/">PhotoApp</a>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
          <% if current_user %>
            <li><%= link_to "Images", "/images"  %></li>
            <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Albums <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <% if current_user.admin? %>
                  <li><%= link_to "Show All Albums", albums_path %></li>
                  <li role="separator" class="divider"></li>
                <% else %>  
                  <li><%= link_to "Albums by: #{current_user.full_name}", albums_path %></li>
                  <li role="separator" class="divider"></li>
                <% end %>  
                    <% Album.all.each do |album| %>
                    <% if current_user.id == album.user_id || current_user.admin? %>
                      <% if current_user.admin? %>
                        <li><%= link_to "#{album.name}: #{User.find(album.user_id).full_name}", album_path(album) %></li>
                       <% else %> 
                       <li><%= link_to "#{album.name}", album_path(album) %></li>
                      <% end %>   
                    <% end %>
                  <% end %>
            <% if current_user %>
              <li role="separator" class="divider"></li>
              <li><%= link_to "Create New Album", new_album_path %></li>
            <% end %>
          </ul>
          </li> 
            <li><%= link_to "Upload Image", "/images/new" %></li>
            <% if current_user.admin %>
            <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Users <span class="caret"></span></a>
              <ul class="dropdown-menu">
                  <li><%= link_to "Show All Users", freeusers_path %></li>
                  <li role="separator" class="divider"></li>
                    <% User.all.each do |user| %>
                    <li>
                      <% if user.admin? %>
                        <%= link_to "Admin User: " + "#{user.full_name}", freeuser_path(user)%>
                      <% else %>
                        <%= link_to "#{user.full_name}", freeuser_path(user)%>
                    </li>
                    <% end %>
                  <% end %>
            <% else %> 
              <% if current_user == User.find_by(email: 'admin@photo-app.com') || current_user == User.find_by(email: 'demo@photo-app.com')%>   
                <li style="margin-top: 16px; margin-left: 20px; color: darkred;"><strong>Demo Account </strong></li>
              <% else %>
                <li><%= link_to "Edit your profile", "/users/edit"  %></li>
              <% end %>
              
              <% end %>
            </ul>
            </li>
            <% if current_user.admin %>
              <li style="margin-top: 16px; color: darkred; font-weight: bold;"><p>Admin User</p></li>        
            <% end %>  
          <% end %>  
          </ul>
          <ul class="">    
              <% if current_user %>
                <%= form_tag(search_freeusers_path, class: "navbar-form navbar-left", role: "search") do %>
                  <div class="form-group">
                    <%= text_field_tag :search_name, nil, placeholder: "Search for Users", class: "form-control"%>
                    <%= submit_tag "Search", class: "btn btn-sm btn-info"%>
                    </div>
                  <% end %>
                <% end %>
              <ul class="nav navbar-right col-md-4">
                <% if current_user %>
                <li class="col-md-8 user-name">
                  <% if current_user == User.find_by(email: 'admin@photo-app.com') || current_user == User.find_by(email: 'demo@photo-app.com')%>
                </li>
                  <% else %>
                  <%= link_to ('<i class="fa fa-user"></i> ' + truncate(current_user.full_name, length: 25)).html_safe, edit_user_registration_path, title: 'Edit Profile'%></li>
                 <% end %>
                <li class="col-md-1">&nbsp;</li> 
                <li class="col-md-3 logout"><%= link_to('Logout', destroy_user_session_path, class: 'btn btn-xs btn-danger', title: 'Logout', :method => :delete) %></li>
                <% else %>
                <li class="col-md-4 pull-right"><%= link_to('Sign In', new_user_session_path, class: 'btn btn-xs btn-primary', title: 'Sign In') %></li>
                <% end %>
              </ul>
            </ul>   
        </div>
      </div>
    </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "PhotoApp" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>
    <%= javascript_include_tag "https://js.stripe.com/v2/" %>
    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>
  <%= render "layouts/header"%>
    <div class="container" style="margin-top: 70px;">
      <div class="row">
        <div class="col-lg-12">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
        
      </div>
      
   <!--    <p>
        <footer>
          </br><p>&copy; Sammy Dallal 2016</p>
        </footer>
      </p> -->

      <!--/row-->

     

    </div> <!-- /container -->

  </body>
</html>